/*
5.1 Створити таблицю описів значень атрибутів екземплярів об'єктів.
*/
CREATE TABLE ATTRIBUTES (
	ATTR_ID NUMBER(10),
	OBJECT_ID NUMBER(20),
	VALUE VARCHAR2(4000),
	DATE_VALUE DATE,
	LIST_VALUE_ID NUMBER(10)
);

ALTER TABLE ATTRIBUTES ADD CONSTRAINT ATTRIBUTES_PK
	PRIMARY KEY (ATTR_ID, OBJECT_ID);
ALTER TABLE ATTRIBUTES ADD CONSTRAINT ATTRIBUTES_LIST_VALUE_ID_FK
	FOREIGN KEY (LIST_VALUE_ID) REFERENCES LISTS (LIST_VALUE_ID);
ALTER TABLE ATTRIBUTES ADD CONSTRAINT ATTRIBUTES_ATTR_ID_FK
	FOREIGN KEY (ATTR_ID) REFERENCES ATTRTYPE (ATTR_ID);
ALTER TABLE ATTRIBUTES ADD CONSTRAINT ATTRIBUTES_OBJECT_ID_FK
	FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS (OBJECT_ID);
/*
Table ATTRIBUTES created.

Table ATTRIBUTES altered.

Table ATTRIBUTES altered.

Table ATTRIBUTES altered.

Table ATTRIBUTES altered.
*/
/*
5.2 На основі вмісту двох рядків двох таблиць, заповнених у лабораторній роботі No3, та опису
атрибутів екземплярів об'єктів, заповнити описи значень атрибутів екземплярів об'єктів.
*/
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (1, 1, 'Mykola', NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (2, 1, 'Heshko', NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (3, 1, '0664241334', NULL, NULL);

INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (1, 2, 'Andrew', NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (2, 2, 'Jackson', NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (3, 2, '0636619513', NULL, NULL);

INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (4, 3, 'Холодильник SAMSUNG', NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (5, 3, 'RB33J3000SA/UA', NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (6, 3, 'Потрібна діагностика', NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (7, 3, 1, NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (8, 3, NULL, '23/03/22', NULL);

INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (4, 4, 'Холодильник Whirlpool', NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (5, 4, 'F00185264', NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (6, 4, 'Потрібна діагностика', NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (7, 4, 1, NULL, NULL);
INSERT INTO ATTRIBUTES (ATTR_ID, OBJECT_ID, VALUE, DATE_VALUE, LIST_VALUE_ID)
VALUES (8, 4, NULL, '23/03/22', NULL);
/*
5.3 Модифікувати рішення завдання 4.3, отримавши колекцію екземплярів об'єктів за заданим
значенням одного з атрибутів об'єктів.
*/
SELECT 
    EQUIPMENT.OBJECT_ID,
    EQUIPMENT.NAME,
    ATTR.VALUE AS SERIAL
FROM OBJECTS EQUIPMENT, OBJTYPE OT, ATTRIBUTES ATTR
WHERE 	
    OT.CODE = 'EQUIPMENT' 
	AND OT.OBJECT_TYPE_ID = EQUIPMENT.OBJECT_TYPE_ID
    AND ATTR.VALUE = 'F00185264'
    AND ATTR.OBJECT_ID = EQUIPMENT.OBJECT_ID;
/*
 OBJECT_ID|NAME        |SERIAL|
 ---------+------------+-----+
         4|Чайник      |F00185264
*/